### ISSUE TITLE
Make activation functions modules?

### ISSUE THREAD

**Issue by ArthurConmy** [neelnanda-io/Easy-Transformer#14]
I was just merging this in, and this:
![Screenshot from 2022-09-16 14-22-26](https://user-images.githubusercontent.com/35957051/190774781-dc766358-ce15-4f73-91d4-bbb22d63c6ff.png)
makes me a bit sad, as I have to think about 4 different activation functions in the otherwise really simple and clean file. Can all the activation functions be made modules instead? Happy to work on this if there's agreement

_Originally posted by @ArthurConmy in https://github.com/neelnanda-io/Easy-Transformer/issues/8#issuecomment-1249829860_

**Comment by anshradh** [comment]
This seems reasonable to me - could just have add the modules in utils along with the functional versions I think?

**Comment by neelnanda-io** [comment]
Agreed it's messy, though seems somewhat hard to solve. The obvious way to make it a module is:
```
pre_act = W_in @ x + b_in
post_act = act_fn(pre_act)
mlp_out = W_out @ post_act + b_out
```

Making SoLU a module works, but making ReGLU, GeGLU and SwiGLU modules doesn't - they need access to x _and_ the pre-act which makes for a messier abstraction (I'm personally fine just deleting ReGLU and GeGLU and SwiGLU lol, since I'm not sure anyone will ever use them). Having an act_fn module with a positional input pre_act and an optional input x would work I guess?

**Comment by neelnanda-io** [comment]
(Another issue is that if you have a hook inside a sub-module, then that hook's name would be ...mlp.act_fn.hook_gate rather than ...mlp.hook_gate, which is mildly irritating to me, esp for SoLU)

**Comment by neelnanda-io** [comment]
An alternate option would be making a GatedMLP, SoLUMLP and normal MLP class, and having TransformerBlock decide which one to use. Though obviously that has issues of its own re duplicated code

**Comment by neelnanda-io** [comment]
I'm pretty confused about which one is best (though personally lean towards deleting the GLUs and keeping SoLU - sorry @anshradh!)

**Comment by anshradh** [comment]
Yeah I share your inclination that no one will really want to use them (except for maybe people who want to make PALM-like models?) so I think it would be reasonable to get rid of the GLUs - no offense taken!

**Comment by neelnanda-io** [comment]
Fixed this
